package main

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"sync"
	"time"
)

// ============================================================================
// 聊天模块（保留）
// ============================================================================

// Message represents a chat message
type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// ChatRequest represents the incoming chat request
type ChatRequest struct {
	Model     string    `json:"model"`
	UserID    string    `json:"userId"`
	SessionID string    `json:"sessionId"`
	Message   string    `json:"message"`
	Stream    bool      `json:"stream"`
	Messages  []Message `json:"messages"`
}

// Session stores conversation history for a session
type Session struct {
	ID        string
	UserID    string
	Messages  []Message
	CreatedAt time.Time
	UpdatedAt time.Time
	mu        sync.RWMutex
}

var (
	sessions = make(map[string]*Session)
	smu      sync.RWMutex
)

// getOrCreateSession gets or creates a session
func getOrCreateSession(userID, sessionID string) *Session {
	smu.Lock()
	defer smu.Unlock()

	key := userID + ":" + sessionID
	if session, exists := sessions[key]; exists {
		session.UpdatedAt = time.Now()
		return session
	}

	session := &Session{
		ID:        sessionID,
		UserID:    userID,
		Messages:  make([]Message, 0),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	sessions[key] = session
	return session
}

// generateResponse generates a simple AI response
func generateResponse(session *Session, userMessage string) string {
	session.mu.Lock()
	defer session.mu.Unlock()

	session.Messages = append(session.Messages, Message{
		Role:    "user",
		Content: userMessage,
	})

	response := generateContextualResponse(userMessage)

	session.Messages = append(session.Messages, Message{
		Role:    "assistant",
		Content: response,
	})

	return response
}

func generateContextualResponse(message string) string {
	msg := strings.ToLower(message)

	if strings.Contains(msg, "hello") || strings.Contains(msg, "hi") {
		return "Hello! I'm your AI assistant. How can I help you today?"
	}
	if strings.Contains(msg, "how are you") {
		return "I'm doing great, thank you for asking! I'm here to help you with any questions you might have."
	}
	if strings.Contains(msg, "bye") || strings.Contains(msg, "goodbye") {
		return "Goodbye! Feel free to come back anytime you need assistance. Have a great day!"
	}
	if strings.Contains(msg, "thank") {
		return "You're welcome! Is there anything else I can help you with?"
	}
	if strings.Contains(msg, "help") {
		return "I can help you with a variety of tasks including:\n- Answering questions\n- Writing code\n- Explaining concepts\n- Brainstorming ideas\n- And much more!\n\nWhat would you like to know?"
	}

	return fmt.Sprintf("I received your message: \"%s\"\n\nThis is a demo response. In production, this would be generated by an AI model. The chat interface supports userId and sessionId for maintaining conversation context across sessions.", message)
}

func chatHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req ChatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	session := getOrCreateSession(req.UserID, req.SessionID)
	response := generateResponse(session, req.Message)

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	flusher, ok := w.(http.Flusher)
	if !ok {
		http.Error(w, "Streaming unsupported", http.StatusInternalServerError)
		return
	}

	// 按 OpenAI 风格发送增量帧：data: {"choices":[{"delta":{"content":"<char>"}}]}\n\n
	// 这样前端可以无差别地复用 OpenAI 兼容的 SSE 解析器
	for _, ch := range chunksOfString(response) {
		frame := map[string]interface{}{
			"choices": []map[string]interface{}{
				{"delta": map[string]string{"content": ch}},
			},
		}
		data, err := json.Marshal(frame)
		if err != nil {
			log.Printf("[chat] marshal frame failed: %v", err)
			continue
		}
		fmt.Fprintf(w, "data: %s\n\n", data)
		flusher.Flush()
		time.Sleep(20 * time.Millisecond)
	}

	// 终止帧：data: [DONE]\n\n
	fmt.Fprintf(w, "data: [DONE]\n\n")
	flusher.Flush()
	log.Printf("[chat] stream done sessionId=%s", req.SessionID)
}

// chunksOfString 将字符串切成字符切片，按 UTF-8 rune 切，避免把多字节字符拆坏
func chunksOfString(s string) []string {
	out := make([]string, 0, len(s))
	for _, r := range s {
		out = append(out, string(r))
	}
	return out
}

func completionsHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req ChatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	session := getOrCreateSession(req.UserID, req.SessionID)
	response := generateResponse(session, req.Message)

	resp := map[string]interface{}{
		"id": fmt.Sprintf("chatcmpl-%d", time.Now().UnixNano()),
		"choices": []map[string]interface{}{
			{
				"message": map[string]string{
					"role":    "assistant",
					"content": response,
				},
				"finish_reason": "stop",
			},
		},
		"usage": map[string]int{
			"prompt_tokens":     10,
			"completion_tokens": len(response) / 4,
			"total_tokens":      10 + len(response)/4,
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func ipHandler(w http.ResponseWriter, r *http.Request) {
	ip := r.Header.Get("X-Forwarded-For")
	if ip == "" {
		ip = r.Header.Get("X-Real-IP")
	}
	if ip == "" {
		addr := r.RemoteAddr
		if strings.HasPrefix(addr, "[") {
			parts := strings.Split(addr, "]")
			if len(parts) > 0 {
				ip = strings.TrimPrefix(parts[0], "[")
			}
		} else {
			ip = strings.Split(addr, ":")[0]
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"ip": ip})
}

// ============================================================================
// 认证模块（新增）
// 数据全部驻留内存：users / authSessions
// 不会主动清理用户记录，确保数据源不丢失
// 仅在每次查询时按 TTL 过滤失效会话
// ============================================================================

// User 内存中的账号信息（密码以 SHA-256 摘要存储）
type User struct {
	ID         int64     `json:"id"`
	Username   string    `json:"username"`
	Password   string    `json:"-"` // 摘要，不返回给前端
	Nickname   string    `json:"nickname"`
	Phone      string    `json:"phone"`
	Email      string    `json:"email"`
	Role       string    `json:"role"`     // user / admin
	Avatar     string    `json:"avatar"`   // emoji 或 URL
	Bio        string    `json:"bio"`      // 个性签名
	Gender     string    `json:"gender"`   // male / female / other
	Birthday   string    `json:"birthday"` // YYYY-MM-DD
	CreatedAt  time.Time `json:"createdAt"`
}

// AuthSession 登录会话
type AuthSession struct {
	SessionID string
	UserID    int64
	ExpiresAt time.Time
}

const (
	sessionTTL  = 1 * time.Hour
	passwordSalt = "echo-web-salt"
)

var (
	authMu       sync.RWMutex
	users        = make(map[string]*User)         // key: username
	usersByID    = make(map[int64]*User)          // key: id
	authSessions = make(map[string]*AuthSession)  // key: sessionId
	nextUserID   int64 = 1
)

// jsonResp 统一响应封装
func jsonResp(w http.ResponseWriter, status int, code int, message string, data interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"code":    code,
		"message": message,
		"data":    data,
	})
}

// jsonOK 成功响应
func jsonOK(w http.ResponseWriter, data interface{}) {
	jsonResp(w, http.StatusOK, 0, "ok", data)
}

// jsonErr 业务错误
func jsonErr(w http.ResponseWriter, status, code int, message string) {
	jsonResp(w, status, code, message, nil)
}

// hashPassword 计算密码摘要
func hashPassword(password string) string {
	h := sha256.Sum256([]byte(password + passwordSalt))
	return hex.EncodeToString(h[:])
}

// randomID 生成随机 sessionId
func randomID() string {
	b := make([]byte, 24)
	rand.Read(b)
	return base64.RawURLEncoding.EncodeToString(b)
}

// sweepSessions 清理过期会话（仅惰性触发）
func sweepSessions() {
	now := time.Now()
	for k, v := range authSessions {
		if now.After(v.ExpiresAt) {
			delete(authSessions, k)
		}
	}
}

// loginRequest 登录入参
type loginRequest struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
}

// loginHandler POST /api/auth/login
func loginHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonErr(w, http.StatusMethodNotAllowed, 405, "Method not allowed")
		return
	}

	var req loginRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, 400, "请求体格式错误")
		return
	}
	req.Username = strings.TrimSpace(req.Username)
	if req.Username == "" || req.Password == "" {
		jsonErr(w, http.StatusBadRequest, 400, "账号和密码不能为空")
		return
	}

	authMu.Lock()
	defer authMu.Unlock()

	// 校验账号密码
	u, exists := users[req.Username]
	if !exists || u.Password != hashPassword(req.Password) {
		jsonErr(w, http.StatusUnauthorized, 401, "账号或密码错误")
		return
	}

	// 创建会话
	sweepSessions()
	sessionID := randomID()
	authSessions[sessionID] = &AuthSession{
		SessionID: sessionID,
		UserID:    u.ID,
		ExpiresAt: time.Now().Add(sessionTTL),
	}

	log.Printf("[auth] login success username=%s sessionId=%s", u.Username, sessionID)
	jsonOK(w, map[string]interface{}{
		"sessionId":  sessionID,
		"expiresAt":  time.Now().Add(sessionTTL).Unix(),
		"expiresIn":  int(sessionTTL.Seconds()),
		"user": map[string]interface{}{
			"id":       u.ID,
			"username": u.Username,
			"nickname": u.Nickname,
			"phone":    u.Phone,
			"email":    u.Email,
			"role":     u.Role,
			"avatar":   u.Avatar,
			"bio":      u.Bio,
			"gender":   u.Gender,
			"birthday": u.Birthday,
		},
	})
}

// registerRequest 注册入参
type registerRequest struct {
	Username   string `json:"username"`
	Password   string `json:"password"`
	Nickname   string `json:"nickname"`
	Phone      string `json:"phone"`
	Email      string `json:"email"`
	Avatar     string `json:"avatar"`
	Bio        string `json:"bio"`
	Gender     string `json:"gender"`
	Birthday   string `json:"birthday"`
}

// registerHandler POST /api/auth/register
func registerHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonErr(w, http.StatusMethodNotAllowed, 405, "Method not allowed")
		return
	}

	var req registerRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, 400, "请求体格式错误")
		return
	}
	req.Username = strings.TrimSpace(req.Username)
	req.Nickname = strings.TrimSpace(req.Nickname)
	req.Phone = strings.TrimSpace(req.Phone)
	req.Email = strings.TrimSpace(req.Email)

	if len(req.Username) < 3 {
		jsonErr(w, http.StatusBadRequest, 400, "账号至少 3 个字符")
		return
	}
	if len(req.Password) < 6 {
		jsonErr(w, http.StatusBadRequest, 400, "密码至少 6 位")
		return
	}
	if req.Nickname == "" {
		req.Nickname = req.Username
	}

	authMu.Lock()
	defer authMu.Unlock()

	// 账号唯一
	if _, exists := users[req.Username]; exists {
		jsonErr(w, http.StatusBadRequest, 400, "该账号已被注册")
		return
	}

	u := &User{
		ID:        nextUserID,
		Username:  req.Username,
		Password:  hashPassword(req.Password),
		Nickname:  req.Nickname,
		Phone:     req.Phone,
		Email:     req.Email,
		Role:      "user",
		Avatar:    req.Avatar,
		Bio:       req.Bio,
		Gender:    req.Gender,
		Birthday:  req.Birthday,
		CreatedAt: time.Now(),
	}
	users[u.Username] = u
	usersByID[u.ID] = u
	nextUserID++

	log.Printf("[auth] register success username=%s id=%d", u.Username, u.ID)
	jsonOK(w, map[string]interface{}{
		"id":       u.ID,
		"username": u.Username,
		"nickname": u.Nickname,
	})
}

// checkRequest 会话校验
type checkRequest struct {
	SessionID string `json:"sessionId"`
}

// checkHandler POST /api/auth/check
func checkHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonErr(w, http.StatusMethodNotAllowed, 405, "Method not allowed")
		return
	}

	var req checkRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, 400, "请求体格式错误")
		return
	}
	if req.SessionID == "" {
		jsonErr(w, http.StatusBadRequest, 400, "缺少 sessionId")
		return
	}

	authMu.RLock()
	sess, ok := authSessions[req.SessionID]
	if !ok || time.Now().After(sess.ExpiresAt) {
		authMu.RUnlock()
		jsonErr(w, http.StatusUnauthorized, 401, "会话已失效，请重新登录")
		return
	}
	u := usersByID[sess.UserID]
	authMu.RUnlock()

	if u == nil {
		jsonErr(w, http.StatusUnauthorized, 401, "账号不存在")
		return
	}
	jsonOK(w, map[string]interface{}{
		"user": map[string]interface{}{
			"id":       u.ID,
			"username": u.Username,
			"nickname": u.Nickname,
			"phone":    u.Phone,
			"email":    u.Email,
			"role":     u.Role,
			"avatar":   u.Avatar,
			"bio":      u.Bio,
			"gender":   u.Gender,
			"birthday": u.Birthday,
		},
		"expiresAt": sess.ExpiresAt.Unix(),
	})
}

// logoutRequest 登出入参
type logoutRequest struct {
	SessionID string `json:"sessionId"`
}

// logoutHandler POST /api/auth/logout
func logoutHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		jsonErr(w, http.StatusMethodNotAllowed, 405, "Method not allowed")
		return
	}
	var req logoutRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, 400, "请求体格式错误")
		return
	}
	authMu.Lock()
	delete(authSessions, req.SessionID)
	authMu.Unlock()
	log.Printf("[auth] logout sessionId=%s", req.SessionID)
	jsonOK(w, map[string]interface{}{"ok": true})
}

// corsMiddleware 允许跨域（前后端分离开发场景）
func corsMiddleware(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Session-Id")
		if r.Method == http.MethodOptions {
			w.WriteHeader(http.StatusNoContent)
			return
		}
		next(w, r)
	}
}

// corsWrap 对 handler 套 CORS
func corsWrap(h http.HandlerFunc) http.HandlerFunc {
	return corsMiddleware(h)
}

func main() {
	// 预置演示账号（仅在内存中）
	demo := &User{
		ID:        nextUserID,
		Username:  "demo",
		Password:  hashPassword("demo123"),
		Nickname:  "演示账号",
		Phone:     "13800000000",
		Email:     "demo@echo.local",
		Role:      "user",
		Avatar:    "🦊",
		Bio:       "虚拟陪伴构建平台演示账号",
		Gender:    "other",
		Birthday:  "2000-01-01",
		CreatedAt: time.Now(),
	}
	users[demo.Username] = demo
	usersByID[demo.ID] = demo
	nextUserID++
	log.Printf("[auth] seeded demo user: username=demo password=demo123")

	// 注册路由
	http.HandleFunc("/api/chat", corsWrap(chatHandler))
	http.HandleFunc("/api/chat/completions", corsWrap(completionsHandler))
	http.HandleFunc("/api/ip", corsWrap(ipHandler))
	http.HandleFunc("/api/auth/login", corsWrap(loginHandler))
	http.HandleFunc("/api/auth/register", corsWrap(registerHandler))
	http.HandleFunc("/api/auth/check", corsWrap(checkHandler))
	http.HandleFunc("/api/auth/logout", corsWrap(logoutHandler))
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Echo Web Backend Server is running!")
	})

	fmt.Println("Server starting on http://localhost:8080")
	fmt.Println("Endpoints:")
	fmt.Println("  POST /api/chat                - Streaming chat")
	fmt.Println("  POST /api/chat/completions    - Non-streaming chat")
	fmt.Println("  GET  /api/ip                  - Get client IP")
	fmt.Println("  POST /api/auth/login          - Login")
	fmt.Println("  POST /api/auth/register       - Register")
	fmt.Println("  POST /api/auth/check          - Validate sessionId")
	fmt.Println("  POST /api/auth/logout         - Logout")
	fmt.Println()
	fmt.Println("Demo user: demo / demo123")

	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}
