package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"sync"
	"time"
)

// Message represents a chat message
type Message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

// ChatRequest represents the incoming chat request
type ChatRequest struct {
	Model     string  `json:"model"`
	UserID    string  `json:"userId"`
	SessionID string  `json:"sessionId"`
	Message   string  `json:"message"`
	Stream    bool    `json:"stream"`
	Messages  []Message `json:"messages"`
}

// Session stores conversation history for a session
type Session struct {
	ID        string
	UserID    string
	Messages  []Message
	CreatedAt time.Time
	UpdatedAt time.Time
	mu        sync.RWMutex
}

var (
	sessions = make(map[string]*Session)
	smu      sync.RWMutex
)

// getOrCreateSession gets or creates a session
func getOrCreateSession(userID, sessionID string) *Session {
	smu.Lock()
	defer smu.Unlock()

	key := userID + ":" + sessionID
	if session, exists := sessions[key]; exists {
		session.UpdatedAt = time.Now()
		return session
	}

	session := &Session{
		ID:        sessionID,
		UserID:    userID,
		Messages:  make([]Message, 0),
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
	}
	sessions[key] = session
	return session
}

// generateResponse generates a simple AI response
func generateResponse(session *Session, userMessage string) string {
	// Simple response logic - in production this would call an AI model
	session.mu.Lock()
	defer session.mu.Unlock()

	// Add user message to history
	session.Messages = append(session.Messages, Message{
		Role:    "user",
		Content: userMessage,
	})

	// Generate a contextual response based on the message
	response := generateContextualResponse(userMessage)

	// Add assistant response to history
	session.Messages = append(session.Messages, Message{
		Role:    "assistant",
		Content: response,
	})

	return response
}

func generateContextualResponse(message string) string {
	msg := strings.ToLower(message)

	if strings.Contains(msg, "hello") || strings.Contains(msg, "hi") {
		return "Hello! I'm your AI assistant. How can I help you today?"
	}

	if strings.Contains(msg, "how are you") {
		return "I'm doing great, thank you for asking! I'm here to help you with any questions you might have."
	}

	if strings.Contains(msg, "bye") || strings.Contains(msg, "goodbye") {
		return "Goodbye! Feel free to come back anytime you need assistance. Have a great day!"
	}

	if strings.Contains(msg, "thank") {
		return "You're welcome! Is there anything else I can help you with?"
	}

	if strings.Contains(msg, "help") {
		return "I can help you with a variety of tasks including:\n- Answering questions\n- Writing code\n- Explaining concepts\n- Brainstorming ideas\n- And much more!\n\nWhat would you like to know?"
	}

	// Default response
	return fmt.Sprintf("I received your message: \"%s\"\n\nThis is a demo response. In production, this would be generated by an AI model. The chat interface supports userId and sessionId for maintaining conversation context across sessions.", message)
}

func chatHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req ChatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Get or create session
	session := getOrCreateSession(req.UserID, req.SessionID)

	// Generate response
	response := generateResponse(session, req.Message)

	// Send streaming response
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	// Stream the response character by character
	chunks := strings.Split(response, "")
	for _, ch := range chunks {
		data, _ := json.Marshal(ch)
		fmt.Fprintf(w, "data: %s\n\n", data)
		w.(http.Flusher).Flush()
		time.Sleep(20 * time.Millisecond)
	}

	// Send completion signal
	fmt.Fprintln(w, "data: [DONE]")
	w.(http.Flusher).Flush()
}

func completionsHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req ChatRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid request body", http.StatusBadRequest)
		return
	}

	// Get or create session
	session := getOrCreateSession(req.UserID, req.SessionID)

	// Generate response
	response := generateResponse(session, req.Message)

	// Return JSON response
	resp := map[string]interface{}{
		"id": fmt.Sprintf("chatcmpl-%d", time.Now().UnixNano()),
		"choices": []map[string]interface{}{
			{
				"message": map[string]string{
					"role":    "assistant",
					"content": response,
				},
				"finish_reason": "stop",
			},
		},
		"usage": map[string]int{
			"prompt_tokens":     10,
			"completion_tokens": len(response) / 4,
			"total_tokens":      10 + len(response)/4,
		},
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(resp)
}

func ipHandler(w http.ResponseWriter, r *http.Request) {
	// Get client IP
	ip := r.Header.Get("X-Forwarded-For")
	if ip == "" {
		ip = r.Header.Get("X-Real-IP")
	}
	if ip == "" {
		// Handle IPv6 addresses like [::1]:port
		addr := r.RemoteAddr
		if strings.HasPrefix(addr, "[") {
			// IPv6 format: [::1]:port
			parts := strings.Split(addr, "]")
			if len(parts) > 0 {
				ip = strings.TrimPrefix(parts[0], "[")
			}
		} else {
			// IPv4 format: ip:port
			ip = strings.Split(addr, ":")[0]
		}
	}

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(map[string]string{"ip": ip})
}

func main() {
	// Register handlers
	http.HandleFunc("/api/chat", chatHandler)
	http.HandleFunc("/api/chat/completions", completionsHandler)
	http.HandleFunc("/api/ip", ipHandler)
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintln(w, "Echo Web Backend Server is running!")
	})

	fmt.Println("Server starting on http://localhost:8080")
	fmt.Println("Endpoints:")
	fmt.Println("  POST /api/chat - Streaming chat")
	fmt.Println("  POST /api/chat/completions - Non-streaming chat")

	if err := http.ListenAndServe(":8080", nil); err != nil {
		log.Fatal(err)
	}
}